/* Generated by bdf2lvgl (https://github.com/summivox/bdf2lvgl) */

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 ' ' */


    /* U+0021 '!' */
    0xff, 0x30,

    /* U+0022 '"' */
    0xee, 0x44, 0x8a, 0x20,

    /* U+0023 '#' */
    0x12, 0x12, 0x12, 0x7f, 0x24, 0x24, 0x24, 0xfe, 0x48, 0x48, 0x48,

    /* U+0024 '$' */
    0x10, 0xfa, 0x4c, 0x89, 0x0e, 0x07, 0x09, 0x13, 0x25, 0xf0, 0x80,

    /* U+0025 '%' */
    0x63, 0x26, 0x53, 0x20, 0x82, 0x04, 0x10, 0x4c, 0xa6, 0x4c, 0x60,

    /* U+0026 '&' */
    0x30, 0x91, 0x22, 0x43, 0x0c, 0x34, 0xc9, 0x8b, 0x17, 0x13, 0xd0,

    /* U+0027 "'" */
    0xd6,

    /* U+0028 '(' */
    0x12, 0x44, 0x88, 0x88, 0x88, 0x44, 0x21,

    /* U+0029 ')' */
    0x84, 0x22, 0x11, 0x11, 0x11, 0x22, 0x48,

    /* U+002A '*' */
    0x25, 0x5c, 0xea, 0x90,

    /* U+002B '+' */
    0x10, 0x20, 0x47, 0xf1, 0x02, 0x04, 0x00,

    /* U+002C ',' */
    0xd6,

    /* U+002D '-' */
    0xf8,

    /* U+002E '.' */
    0xfc,

    /* U+002F '/' */
    0x08, 0x44, 0x21, 0x10, 0x88, 0x42, 0x21, 0x00,

    /* U+0030 '0' */
    0x38, 0x8a, 0x0c, 0x18, 0xb2, 0x64, 0xd1, 0x83, 0x05, 0x11, 0xc0,

    /* U+0031 '1' */
    0x35, 0x91, 0x11, 0x11, 0x11, 0x11,

    /* U+0032 '2' */
    0x7a, 0x10, 0x41, 0x08, 0x42, 0x10, 0x42, 0x08, 0x3f,

    /* U+0033 '3' */
    0x7a, 0x10, 0x41, 0x04, 0xe0, 0x41, 0x04, 0x18, 0x5e,

    /* U+0034 '4' */
    0x08, 0x61, 0x8a, 0x29, 0x24, 0xa2, 0xfc, 0x20, 0x82,

    /* U+0035 '5' */
    0xfe, 0x08, 0x20, 0xf8, 0x10, 0x41, 0x04, 0x18, 0x5e,

    /* U+0036 '6' */
    0x7a, 0x18, 0x20, 0x83, 0xe8, 0x61, 0x86, 0x18, 0x5e,

    /* U+0037 '7' */
    0xfc, 0x10, 0x42, 0x08, 0x41, 0x04, 0x20, 0x82, 0x08,

    /* U+0038 '8' */
    0x7a, 0x18, 0x61, 0x85, 0xe8, 0x61, 0x86, 0x18, 0x5e,

    /* U+0039 '9' */
    0x7a, 0x18, 0x61, 0x86, 0x17, 0xc1, 0x04, 0x18, 0x5e,

    /* U+003A ':' */
    0xf0, 0x0f,

    /* U+003B ';' */
    0xf0, 0x0d, 0x80,

    /* U+003C '<' */
    0x08, 0x88, 0x88, 0x20, 0x82, 0x08,

    /* U+003D '=' */
    0xfc, 0x00, 0x00, 0xfc,

    /* U+003E '>' */
    0x82, 0x08, 0x20, 0x88, 0x88, 0x80,

    /* U+003F '?' */
    0x7a, 0x10, 0x41, 0x04, 0x21, 0x08, 0x00, 0x02, 0x08,

    /* U+0040 '@' */
    0x7a, 0x18, 0x61, 0x9e, 0x9a, 0x69, 0x9e, 0x08, 0x1e,

    /* U+0041 'A' */
    0x31, 0x24, 0x92, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,

    /* U+0042 'B' */
    0xfa, 0x18, 0x61, 0x87, 0xe8, 0x61, 0x86, 0x18, 0x7e,

    /* U+0043 'C' */
    0x7a, 0x18, 0x20, 0x82, 0x08, 0x20, 0x82, 0x08, 0x5e,

    /* U+0044 'D' */
    0xf2, 0x28, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0xbc,

    /* U+0045 'E' */
    0xfc, 0x21, 0x08, 0x7a, 0x10, 0x84, 0x21, 0xf0,

    /* U+0046 'F' */
    0xfc, 0x21, 0x0f, 0x42, 0x10, 0x84, 0x21, 0x00,

    /* U+0047 'G' */
    0x7a, 0x18, 0x20, 0x82, 0x08, 0x23, 0x86, 0x18, 0x5e,

    /* U+0048 'H' */
    0x86, 0x18, 0x61, 0x87, 0xf8, 0x61, 0x86, 0x18, 0x61,

    /* U+0049 'I' */
    0xf9, 0x08, 0x42, 0x10, 0x84, 0x21, 0x09, 0xf0,

    /* U+004A 'J' */
    0xfc, 0x10, 0x41, 0x04, 0x10, 0x41, 0x06, 0x18, 0x5e,

    /* U+004B 'K' */
    0x86, 0x18, 0xa4, 0x92, 0x8e, 0x24, 0x8a, 0x28, 0x61,

    /* U+004C 'L' */
    0x82, 0x08, 0x20, 0x82, 0x08, 0x20, 0x82, 0x08, 0x3f,

    /* U+004D 'M' */
    0x83, 0x8e, 0xad, 0x59, 0x30, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x10,

    /* U+004E 'N' */
    0x87, 0x1a, 0x69, 0x96, 0x58, 0xe1, 0x86, 0x18, 0x61,

    /* U+004F 'O' */
    0x7a, 0x18, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,

    /* U+0050 'P' */
    0xfa, 0x18, 0x61, 0x87, 0xe8, 0x20, 0x82, 0x08, 0x20,

    /* U+0051 'Q' */
    0x7a, 0x18, 0x61, 0x86, 0x18, 0x61, 0x86, 0x58, 0x9d,

    /* U+0052 'R' */
    0xfa, 0x18, 0x61, 0x87, 0xe8, 0xa2, 0x8a, 0x18, 0x61,

    /* U+0053 'S' */
    0x7a, 0x18, 0x20, 0x40, 0xc0, 0x81, 0x04, 0x18, 0x5e,

    /* U+0054 'T' */
    0xfe, 0x20, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,

    /* U+0055 'U' */
    0x86, 0x18, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,

    /* U+0056 'V' */
    0x83, 0x06, 0x0c, 0x14, 0x48, 0x91, 0x14, 0x28, 0x50, 0x40, 0x80,

    /* U+0057 'W' */
    0x83, 0x06, 0x0c, 0x18, 0x30, 0x64, 0xc9, 0xab, 0x55, 0x12, 0x20,

    /* U+0058 'X' */
    0x83, 0x05, 0x12, 0x22, 0x82, 0x04, 0x14, 0x28, 0x8a, 0x0c, 0x10,

    /* U+0059 'Y' */
    0x83, 0x05, 0x12, 0x22, 0x85, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,

    /* U+005A 'Z' */
    0xfc, 0x10, 0x42, 0x10, 0x42, 0x10, 0x42, 0x08, 0x3f,

    /* U+005B '[' */
    0xf2, 0x49, 0x24, 0x92, 0x4e,

    /* U+005C '\\' */
    0x84, 0x10, 0x84, 0x10, 0x82, 0x10, 0x82, 0x10,

    /* U+005D ']' */
    0xe4, 0x92, 0x49, 0x24, 0x9e,

    /* U+005E '^' */
    0x22, 0x95, 0x18, 0x80,

    /* U+005F '_' */
    0xfe,

    /* U+0060 '`' */
    0x88, 0x80,

    /* U+0061 'a' */
    0x7a, 0x10, 0x41, 0x7e, 0x18, 0x63, 0x74,

    /* U+0062 'b' */
    0x82, 0x08, 0x2e, 0xc6, 0x18, 0x61, 0x86, 0x1c, 0x6e,

    /* U+0063 'c' */
    0x7a, 0x18, 0x20, 0x82, 0x08, 0x21, 0x78,

    /* U+0064 'd' */
    0x04, 0x10, 0x5d, 0x8e, 0x18, 0x61, 0x86, 0x18, 0xdd,

    /* U+0065 'e' */
    0x7a, 0x18, 0x61, 0xfe, 0x08, 0x21, 0x78,

    /* U+0066 'f' */
    0x1c, 0x82, 0x08, 0xfc, 0x82, 0x08, 0x20, 0x82, 0x08,

    /* U+0067 'g' */
    0x7f, 0x0a, 0x14, 0x27, 0x90, 0x20, 0x3e, 0x83, 0x06, 0x0b, 0xe0,

    /* U+0068 'h' */
    0x82, 0x08, 0x2e, 0xc6, 0x18, 0x61, 0x86, 0x18, 0x61,

    /* U+0069 'i' */
    0x20, 0x01, 0xc2, 0x10, 0x84, 0x21, 0x09, 0xf0,

    /* U+006A 'j' */
    0x08, 0x00, 0x70, 0x84, 0x21, 0x08, 0x42, 0x18, 0xb8,

    /* U+006B 'k' */
    0x82, 0x08, 0x21, 0x8a, 0x4a, 0x38, 0x92, 0x28, 0x61,

    /* U+006C 'l' */
    0xe1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x09, 0xf0,

    /* U+006D 'm' */
    0xed, 0x26, 0x4c, 0x99, 0x32, 0x64, 0xc9, 0x92,

    /* U+006E 'n' */
    0xbb, 0x18, 0x61, 0x86, 0x18, 0x61, 0x84,

    /* U+006F 'o' */
    0x7a, 0x18, 0x61, 0x86, 0x18, 0x61, 0x78,

    /* U+0070 'p' */
    0xbb, 0x18, 0x61, 0x86, 0x18, 0x71, 0xba, 0x08, 0x20,

    /* U+0071 'q' */
    0x76, 0x38, 0x61, 0x86, 0x18, 0x63, 0x74, 0x10, 0x41,

    /* U+0072 'r' */
    0xbb, 0x18, 0x20, 0x82, 0x08, 0x20, 0x80,

    /* U+0073 's' */
    0x7a, 0x18, 0x20, 0x78, 0x10, 0x61, 0x78,

    /* U+0074 't' */
    0x20, 0x82, 0x3f, 0x20, 0x82, 0x08, 0x20, 0x82, 0x07,

    /* U+0075 'u' */
    0x86, 0x18, 0x61, 0x86, 0x18, 0x63, 0x74,

    /* U+0076 'v' */
    0x83, 0x06, 0x0a, 0x24, 0x45, 0x0a, 0x14, 0x10,

    /* U+0077 'w' */
    0x83, 0x06, 0x0c, 0x19, 0x35, 0x6a, 0xa2, 0x44,

    /* U+0078 'x' */
    0x83, 0x05, 0x11, 0x41, 0x05, 0x11, 0x41, 0x82,

    /* U+0079 'y' */
    0x83, 0x05, 0x12, 0x22, 0x85, 0x04, 0x08, 0x20, 0x41, 0x02, 0x00,

    /* U+007A 'z' */
    0xfc, 0x10, 0x84, 0x20, 0x84, 0x20, 0xfc,

    /* U+007B '{' */
    0x72, 0x44, 0xa2, 0x52, 0x46,

    /* U+007C '|' */
    0xff, 0xf0,

    /* U+007D '}' */
    0xc4, 0x94, 0x8a, 0x44, 0x9c,

    /* U+007E '~' */
    0x61, 0x24, 0x30,

};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},  /* U+0000 '\x00' */
    {.bitmap_index = 0, .adv_w = 144, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},  /* U+0020 ' ' */
    {.bitmap_index = 0, .adv_w = 144, .box_w = 1, .box_h = 12, .ofs_x = 4, .ofs_y = 0},  /* U+0021 '!' */
    {.bitmap_index = 2, .adv_w = 144, .box_w = 7, .box_h = 4, .ofs_x = 0, .ofs_y = 8},  /* U+0022 '"' */
    {.bitmap_index = 6, .adv_w = 144, .box_w = 8, .box_h = 11, .ofs_x = 0, .ofs_y = 0},  /* U+0023 '#' */
    {.bitmap_index = 17, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0024 '$' */
    {.bitmap_index = 28, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0025 '%' */
    {.bitmap_index = 39, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0026 '&' */
    {.bitmap_index = 50, .adv_w = 144, .box_w = 2, .box_h = 4, .ofs_x = 2, .ofs_y = 8},  /* U+0027 "'" */
    {.bitmap_index = 51, .adv_w = 144, .box_w = 4, .box_h = 14, .ofs_x = 1, .ofs_y = -1},  /* U+0028 '(' */
    {.bitmap_index = 58, .adv_w = 144, .box_w = 4, .box_h = 14, .ofs_x = 1, .ofs_y = -1},  /* U+0029 ')' */
    {.bitmap_index = 65, .adv_w = 144, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 4},  /* U+002A '*' */
    {.bitmap_index = 69, .adv_w = 144, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 2},  /* U+002B '+' */
    {.bitmap_index = 76, .adv_w = 144, .box_w = 2, .box_h = 4, .ofs_x = 2, .ofs_y = -1},  /* U+002C ',' */
    {.bitmap_index = 77, .adv_w = 144, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 5},  /* U+002D '-' */
    {.bitmap_index = 78, .adv_w = 144, .box_w = 2, .box_h = 3, .ofs_x = 2, .ofs_y = 0},  /* U+002E '.' */
    {.bitmap_index = 79, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+002F '/' */
    {.bitmap_index = 87, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0030 '0' */
    {.bitmap_index = 98, .adv_w = 144, .box_w = 4, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0031 '1' */
    {.bitmap_index = 104, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0032 '2' */
    {.bitmap_index = 113, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0033 '3' */
    {.bitmap_index = 122, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0034 '4' */
    {.bitmap_index = 131, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0035 '5' */
    {.bitmap_index = 140, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0036 '6' */
    {.bitmap_index = 149, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0037 '7' */
    {.bitmap_index = 158, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0038 '8' */
    {.bitmap_index = 167, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0039 '9' */
    {.bitmap_index = 176, .adv_w = 144, .box_w = 2, .box_h = 8, .ofs_x = 3, .ofs_y = 1},  /* U+003A ':' */
    {.bitmap_index = 178, .adv_w = 144, .box_w = 2, .box_h = 9, .ofs_x = 3, .ofs_y = 0},  /* U+003B ';' */
    {.bitmap_index = 181, .adv_w = 144, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 1},  /* U+003C '<' */
    {.bitmap_index = 187, .adv_w = 144, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 3},  /* U+003D '=' */
    {.bitmap_index = 191, .adv_w = 144, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 1},  /* U+003E '>' */
    {.bitmap_index = 197, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+003F '?' */
    {.bitmap_index = 206, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0040 '@' */
    {.bitmap_index = 215, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0041 'A' */
    {.bitmap_index = 224, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0042 'B' */
    {.bitmap_index = 233, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0043 'C' */
    {.bitmap_index = 242, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0044 'D' */
    {.bitmap_index = 251, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0045 'E' */
    {.bitmap_index = 259, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0046 'F' */
    {.bitmap_index = 267, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0047 'G' */
    {.bitmap_index = 276, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0048 'H' */
    {.bitmap_index = 285, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0049 'I' */
    {.bitmap_index = 293, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004A 'J' */
    {.bitmap_index = 302, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004B 'K' */
    {.bitmap_index = 311, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004C 'L' */
    {.bitmap_index = 320, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004D 'M' */
    {.bitmap_index = 331, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004E 'N' */
    {.bitmap_index = 340, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+004F 'O' */
    {.bitmap_index = 349, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0050 'P' */
    {.bitmap_index = 358, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0051 'Q' */
    {.bitmap_index = 367, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0052 'R' */
    {.bitmap_index = 376, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0053 'S' */
    {.bitmap_index = 385, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0054 'T' */
    {.bitmap_index = 396, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0055 'U' */
    {.bitmap_index = 405, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0056 'V' */
    {.bitmap_index = 416, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0057 'W' */
    {.bitmap_index = 427, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0058 'X' */
    {.bitmap_index = 438, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0059 'Y' */
    {.bitmap_index = 449, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+005A 'Z' */
    {.bitmap_index = 458, .adv_w = 144, .box_w = 3, .box_h = 13, .ofs_x = 2, .ofs_y = 0},  /* U+005B '[' */
    {.bitmap_index = 463, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+005C '\\' */
    {.bitmap_index = 471, .adv_w = 144, .box_w = 3, .box_h = 13, .ofs_x = 2, .ofs_y = 0},  /* U+005D ']' */
    {.bitmap_index = 476, .adv_w = 144, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 7},  /* U+005E '^' */
    {.bitmap_index = 480, .adv_w = 144, .box_w = 7, .box_h = 1, .ofs_x = 0, .ofs_y = 0},  /* U+005F '_' */
    {.bitmap_index = 481, .adv_w = 144, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 10},  /* U+0060 '`' */
    {.bitmap_index = 483, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0061 'a' */
    {.bitmap_index = 490, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0062 'b' */
    {.bitmap_index = 499, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0063 'c' */
    {.bitmap_index = 506, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0064 'd' */
    {.bitmap_index = 515, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0065 'e' */
    {.bitmap_index = 522, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0066 'f' */
    {.bitmap_index = 531, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -3},  /* U+0067 'g' */
    {.bitmap_index = 542, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0068 'h' */
    {.bitmap_index = 551, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+0069 'i' */
    {.bitmap_index = 559, .adv_w = 144, .box_w = 5, .box_h = 14, .ofs_x = 1, .ofs_y = -2},  /* U+006A 'j' */
    {.bitmap_index = 568, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+006B 'k' */
    {.bitmap_index = 577, .adv_w = 144, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},  /* U+006C 'l' */
    {.bitmap_index = 585, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+006D 'm' */
    {.bitmap_index = 593, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+006E 'n' */
    {.bitmap_index = 600, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+006F 'o' */
    {.bitmap_index = 607, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = -3},  /* U+0070 'p' */
    {.bitmap_index = 616, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = -3},  /* U+0071 'q' */
    {.bitmap_index = 625, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0072 'r' */
    {.bitmap_index = 632, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0073 's' */
    {.bitmap_index = 639, .adv_w = 144, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = 0},  /* U+0074 't' */
    {.bitmap_index = 648, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0075 'u' */
    {.bitmap_index = 655, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0076 'v' */
    {.bitmap_index = 663, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0077 'w' */
    {.bitmap_index = 671, .adv_w = 144, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+0078 'x' */
    {.bitmap_index = 679, .adv_w = 144, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -3},  /* U+0079 'y' */
    {.bitmap_index = 690, .adv_w = 144, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},  /* U+007A 'z' */
    {.bitmap_index = 697, .adv_w = 144, .box_w = 3, .box_h = 13, .ofs_x = 2, .ofs_y = 0},  /* U+007B '{' */
    {.bitmap_index = 702, .adv_w = 144, .box_w = 1, .box_h = 12, .ofs_x = 3, .ofs_y = 0},  /* U+007C '|' */
    {.bitmap_index = 704, .adv_w = 144, .box_w = 3, .box_h = 13, .ofs_x = 3, .ofs_y = 0},  /* U+007D '}' */
    {.bitmap_index = 709, .adv_w = 144, .box_w = 7, .box_h = 3, .ofs_x = 0, .ofs_y = 4},  /* U+007E '~' */
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

#if LV_VERSION_CHECK(8, 0, 0)
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
};

/*Initialize a public general font descriptor*/
#if LV_VERSION_CHECK(8, 0, 0)
const lv_font_t haxor18 = {
#else
lv_font_t haxor18 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 18,          /*The maximum line height required by the font*/
    .base_line = 3,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0)
    .underline_position = 0,
    .underline_thickness = 0,
#endif
    .dsc = &font_dsc           /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
};
