/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v13.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 14.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 1994d53c-efa9-4d16-89d1-9d5f6fa79147
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO1_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO1_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int0: 'false'
    - gpio_interrupt_int0:
      - IRQn: 'GPIO1_INT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int1: 'false'
    - gpio_interrupt_int1:
      - IRQn: 'GPIO1_INT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int2: 'false'
    - gpio_interrupt_int2:
      - IRQn: 'GPIO1_INT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int3: 'false'
    - gpio_interrupt_int3:
      - IRQn: 'GPIO1_INT3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int4: 'false'
    - gpio_interrupt_int4:
      - IRQn: 'GPIO1_INT4_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int5: 'false'
    - gpio_interrupt_int5:
      - IRQn: 'GPIO1_INT5_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int6: 'false'
    - gpio_interrupt_int6:
      - IRQn: 'GPIO1_INT6_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int7: 'false'
    - gpio_interrupt_int7:
      - IRQn: 'GPIO1_INT7_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO1_init(void) {
  /* Make sure, the clock gate for GPIO1 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO1_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO1_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO1_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO1_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * GPIO2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO2'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO2'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO2_Combined_0_15_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO2_Combined_16_31_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO2_init(void) {
  /* Make sure, the clock gate for GPIO2 is enabled (e. g. in pin_mux.c) */
  /* Interrupt GPIO2_Combined_0_15_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO2_GPIO_COMB_0_15_IRQN);  function call. */
  /* Interrupt GPIO2_Combined_16_31_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(GPIO2_GPIO_COMB_16_31_IRQN);  function call. */
}

/***********************************************************************************************************************
 * TRNG initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TRNG'
- type: 'trng'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'trng_b11006dc1e99bc2587291a4f4a561256'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TRNG'
- config_sets:
  - fsl_trng:
    - settings_trng_config_t:
      - clockMode: 'kTRNG_ClockModeRingOscillator'
      - clockSource: 'BusInterfaceClock'
      - struct_ring_oscillator:
        - ringOscDiv: 'kTRNG_RingOscDiv0'
        - sampleMode: 'kTRNG_SampleModeVonNeumannRaw'
      - entropyDelay: '3200'
      - sampleSize: '2500'
      - sparseBitLimit: '63'
      - retryCount: '1'
      - lock: 'false'
      - struct_statistical_checks:
        - longRunMaxLimit: '34'
        - monobitLimit:
          - maximum: '1384'
          - minimum: '1116'
        - runBit1Limit:
          - maximum: '405'
          - minimum: '227'
        - runBit2Limit:
          - maximum: '220'
          - minimum: '98'
        - runBit3Limit:
          - maximum: '125'
          - minimum: '37'
        - runBit4Limit:
          - maximum: '75'
          - minimum: '11'
        - runBit5Limit:
          - maximum: '47'
          - minimum: '1'
        - runBit6PlusLimit:
          - maximum: '47'
          - minimum: '1'
        - pokerLimit:
          - maximum: '26912'
          - minimum: '24445'
        - frequencyCountLimit:
          - maximum: '25600'
          - minimum: '1600'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const trng_config_t TRNG_config = {
  .lock = false,
  .clockMode = kTRNG_ClockModeRingOscillator,
  .ringOscDiv = kTRNG_RingOscDiv0,


  .sampleMode = kTRNG_SampleModeVonNeumannRaw,
  .entropyDelay = 3200,
  .sampleSize = 2500,
  .sparseBitLimit = 63,
  .retryCount = 1,
  .longRunMaxLimit = 34U,
  .monobitLimit = {
    .maximum = 1384UL,
    .minimum = 1116UL
  },
  .runBit1Limit = {
    .maximum = 405UL,
    .minimum = 227UL
  },
  .runBit2Limit = {
    .maximum = 220UL,
    .minimum = 98UL
  },
  .runBit3Limit = {
    .maximum = 125UL,
    .minimum = 37UL
  },
  .runBit4Limit = {
    .maximum = 75UL,
    .minimum = 11UL
  },
  .runBit5Limit = {
    .maximum = 47UL,
    .minimum = 1UL
  },
  .runBit6PlusLimit = {
    .maximum = 47UL,
    .minimum = 1UL
  },
  .pokerLimit = {
    .maximum = 26912UL,
    .minimum = 24445UL
  },
  .frequencyCountLimit = {
    .maximum = 25600UL,
    .minimum = 1600UL
  }
};

static void TRNG_init(void) {
  /* Initialize TRNG. */
  TRNG_Init(TRNG_PERIPHERAL, &TRNG_config);
}

/***********************************************************************************************************************
 * GPT2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPT2'
- type: 'gpt'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT2'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Periph'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - oscDivider: '1'
      - divider: '75'
      - enableFreeRun: 'true'
      - enableRunInWait: 'true'
      - enableRunInStop: 'true'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'true'
      - enableMode: 'true'
    - input_capture_channels:
      - 0:
        - channelName: 'IMU_INT'
        - channel: 'kGPT_InputCapture_Channel2'
        - mode: 'kGPT_InputOperation_RiseEdge'
    - output_compare_channels: []
    - interrupt_requests: ''
    - isInterruptEnabled: 'false'
    - interrupt:
      - IRQn: 'GPT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t GPT2_config = {
  .clockSource = kGPT_ClockSource_Periph,
  .divider = 75UL,
  .enableFreeRun = true,
  .enableRunInWait = true,
  .enableRunInStop = true,
  .enableRunInDoze = false,
  .enableRunInDbg = true,
  .enableMode = true
};

static void GPT2_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(GPT2_PERIPHERAL, &GPT2_config);
  GPT_SetOscClockDivider(GPT2_PERIPHERAL, 1);
  GPT_SetInputOperationMode(GPT2_PERIPHERAL, kGPT_InputCapture_Channel2, kGPT_InputOperation_RiseEdge);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(GPT2_PERIPHERAL, 0);
  /* Start the GPT timer */ 
  GPT_StartTimer(GPT2_PERIPHERAL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  GPIO1_init();
  GPIO2_init();
  TRNG_init();
  GPT2_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
